/*
 * common.h
 *
 * Created: 26.09.2016 18:09:31
 *  Author: Oleksandr
 */ 


#ifndef COMMON_H_
#define COMMON_H_

#define TRUE	1
#define FALSE	0

#define D_CLK_DDR	DDRB
#define D_CLK_PORT	PORTB
#define D_CLK_PIN	PINB5

#define D_DATA_DDR	DDRB
#define D_DATA_PORT	PORTB
#define D_DATA_PIN	PINB3

#define D_UPD_DDR	DDRB
#define D_UPD_PORT	PORTB
#define D_UPD_PIN	PINB2

typedef enum
{
	TIME_GET_IDLE,
	TIME_GET_START_SYM,
	TIME_GET_HOURS10,
	TIME_GET_HOURS1,
	TIME_GET_SEPARATOR1,
	TIME_GET_MINUTES10,
	TIME_GET_MINUTES1,
	TIME_GET_SEPARATOR2,
	TIME_GET_SECONDS10,
	TIME_GET_SECONDS1,
	TIME_GET_STATE_NUM
}timeGetState_type;


#endif /* COMMON_H_ */